### ISSUE TITLE
XCLocalSwiftPackageReference is not supported

### ISSUE THREAD

**Issue by bennokress** [mattmassicotte/XCLint#14]
I just tested XCLint on a bigger project and got the following error:

> Error: The element XCLocalSwiftPackageReference is not supported.

I'm not complaining, I know the tool is still in development, but I thought you might want to know about error messages from other projects. Let me know if I can give you more info.

**Comment by mattmassicotte** [comment]
Huh! Thank you so much for this report. I’ll definitely investigate.

**Comment by mattmassicotte** [comment]
This was fixed by https://github.com/tuist/XcodeProj/releases/tag/8.16.0. I've updated that dependency to pull in the fix. How does it look for you now?

**Comment by mattmassicotte** [comment]
I believe this was fixed by that release. But, if you see this again, please let me know!
