### ISSUE TITLE
Unactionable errors/warnings

### ISSUE THREAD

**Issue by tonyarnold** [mattmassicotte/XCLint#15]
Hey Mattie, I ❤️ that you've built this! 

Unfortunately, I'm getting some warnings/output that isn't super useful on it's own - it'd be great to see the warnings here expanded and formatted a bit to include info on what/how to remediate: 

```
MyProject-Debug
xcconfig includes unsupported
xcconfig includes unsupported
MyProject, Debug, [:]
MyProject-Release
xcconfig includes unsupported
xcconfig includes unsupported
MyProject, Release, [:]
MyProject Tests-Debug
xcconfig includes unsupported
xcconfig includes unsupported
MyProject Tests, Debug, [:]
MyProject Tests-Release
xcconfig includes unsupported
xcconfig includes unsupported
MyProject Tests, Release, [:]
MyProject UITests-Debug
xcconfig includes unsupported
xcconfig includes unsupported
MyProject UITests, Debug, [:]
MyProject UITests-Release
xcconfig includes unsupported
xcconfig includes unsupported
MyProject UITests, Release, [:]
Group "???" contains unsorted children
Group "???" contains unsorted children
Group "???" contains unsorted children
```

**Comment by mattmassicotte** [comment]
First, thank you so much! Both for the words, but also for filing this issue. It's just so helpful to know that people are trying it and what problems they are seeing.

There are three sources of problems here. I accidentally left in some debug logging. Just fixed that with 3193eca2b3a0e1f5891d5709ba8daf1b782476a7.

The "xcconfig includes unsupported" is coming from the XCConfig project as part of the xcconfig evaluation process. I haven't gotten to actually processing `#include` directives. Opened an issue for that one. https://github.com/mattmassicotte/XCConfig/issues/1

And finally, there's the "Group "???" contains unsorted children". This is an actual rule violation, being reported from the `groups_sorted` rule. It isn't able to resolve the group path for some reason. I'm not super-familiar with this bit of code. It is telling you that one of the groups are in an order that does not match what Xcode will write out. My understanding is this can happen during a manual conflict merge. Could that have happened at some point?

**Comment by tonyarnold** [comment]
Thanks for all of that info, and the fixes/issues! 

> And finally, there's the "Group "???" contains unsorted children". This is an actual rule violation, being reported from the `groups_sorted` rule. It isn't able to resolve the group path for some reason. I'm not super-familiar with this bit of code. It is telling you that one of the groups are in an order that does not match what Xcode will write out. My understanding is this can happen during a manual conflict merge. Could that have happened at some point?

No, I'm not sure that it could have happened. This is a brand new (as of last week) project. 

Here's an image of the structure:

![CleanShot 2023-12-11 at 12 01 56@2x](https://github.com/mattmassicotte/XCLint/assets/4802/757388d8-bab5-4dd9-9886-a1838afabfd5)

Could it be the included Swift Package?

**Comment by mattmassicotte** [comment]
This test is evaluating content in the xcodeproj file. The UI ordering you see will not be affected, but future modifications to the file can exhibit this issue. I'm not saying this violation is correct, or even that I fully understand it. But I do know that you cannot determine this from the Xcode UI.

I'm going to add some additional logging to this rule system, as other issues have come up too.

(Oh! And if you have any interest in poking around on this project, I'd be happy to help you get going with an issue!)

**Comment by mattmassicotte** [comment]
And another update in that addresses the inability to resolve xcconfig includes!

I think this should leave only the `Group "???" contains unsorted children` problem. Can you confirm that? I'd like to look into that next.

**Comment by mattmassicotte** [comment]
I think I've figured out why that error is happening, and I've addressed it with 09266bd40c7b44c3802e8136495130bbfffbb51c. @tonyarnold can you give this another shot?

**Comment by tonyarnold** [comment]
Hey Matt, I'd be happy to! It'll be a couple of days, though, as I'm currently on a family holiday. I'll test the fixes as soon as I'm home.

**Comment by mattmassicotte** [comment]
Absolutely no rush at all!

**Comment by tonyarnold** [comment]
Yeah, that absolutely fixed it! Well done :tada:

**Comment by mattmassicotte** [comment]
Fantastic!
