### ISSUE TITLE
Error: The file “Project.xcconfig” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by leberwurstsaft** [mattmassicotte/XCLint#16]
Running this in our repo only outputs this error.

`Error: The file “Project.xcconfig” couldn’t be opened because there is no such file.`

Indeed, there's no `Project.xcconfig` at the root level. But we do have a few in several directories, nested in like this:
>./Configs/Release/Project.xcconfig
./Configs/Shared/Project.xcconfig
./Configs/TestFlight-Internal/Project.xcconfig
./Configs/Ad-Hoc/Project.xcconfig
./Configs/Debug/Project.xcconfig

Where is xclint getting the name and what are the assumptions to make it look in the root directory?

**Comment by mattmassicotte** [comment]
XCLint inspects the project and traverses the target/build configuration structures. It then attempts to resolve the build settings by emulating how Xcode does it. But that's still a work in progress. I've been actively working on xcconfig resolution recently, and in fact just merged in some work today! But clearly there are some issues.

Thank you so much for taking the time to report this. I'm going to try to reproduce your setup more closely and see if I can reproduce the issue.

**Comment by mattmassicotte** [comment]
Actually question: do any of those files use `#include`? I think I have some overly simplistic path resolution going on…

**Comment by tonyarnold** [comment]
I'm seeing the same thing, and yes, my Release/Debug xcconfigs include a Shared xcconfig.

**Comment by leberwurstsaft** [comment]
[Configs.zip](https://github.com/mattmassicotte/XCLint/files/13901476/Configs.zip)
Prepared a simplified version of our setup and stripped it of all the "secrets". Maybe this can help?

**Comment by mattmassicotte** [comment]
Thank you for that! It actually did help!

I *think* have have fixed this particular issue with d255ebe370a727fc831fdba9288bc236fbf930d9, but I wouldn't be surprised if there are others. I'd love to hear the results @tonyarnold and @leberwurstsaft . You'll have to update to get it.

**Comment by mattmassicotte** [comment]
actually no, tests all pass but some problems remain 😭

**Comment by mattmassicotte** [comment]
Put some notes in https://github.com/mattmassicotte/XCConfig/issues/1. I actually think this may work property now. Please me know!

**Comment by mattmassicotte** [comment]
thank you so much for trying! I *thought* I was handling optional includes correctly, but I guess not...

**Comment by mattmassicotte** [comment]
Definitely was wrong. Version 0.1.1 is now available and hopefully addresses this. But, I suspect it will just uncover another latent issue. I really appreciate your patience.

**Comment by leberwurstsaft** [comment]
After reinstalling (brew upgrade didn't install the new version :suspect:) it finally worked. No errors, no other output.

I then checked out the opt in rules, and sure enough, some output was generated.

Question: Can you elaborate a bit on the "Find implicit dependencies" rule? Is there a downside to those or why should we care?

**Comment by mattmassicotte** [comment]
Whew, thank you for help with this. The "no output" is expected when no errors are found. Just a 0 status code.

The downside of "implicit dependencies" is you may not fully understand you project's real dependency graph. This means that subtle changes to your Xcode project could break a target build. And, in a way that you might not even notice until you clean. Apple includes it to try to make this work more automatically in more cases. And I'm sure it does that. So it is a trade-off. But if you want to be sure you **really know** what is required to get your project to build, you have to turn that off.

**Comment by leberwurstsaft** [comment]
Thanks for that explanation. I'll try and see what happens when we turn it off.

**Comment by mattmassicotte** [comment]
You are very welcome! Let me know if anything else comes up!
