### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by mattmassicotte** [mattmassicotte/XCLint#2]
I'd like to figure out how to get this installable with a homebrew [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). This will make it a lot easier for people to use, and will also help prove out an end-to-end system.

**Comment by mattmassicotte** [comment]
This is turning out to be much more difficult that I expected. I made a formula, and this part *seemed* easy.

Here's what's happening:

```
brew install -v -n Forumla/xclint.rb
Error: Failed to load cask: Forumla/xclint.rb
Cask 'xclint' is unreadable: wrong constant name #<Class:0x00000001587e7f30>
Warning: Treating Forumla/xclint.rb as a formula.
==> Would install 1 formula:
xclint
```

Bizarrely, despite the error, this successfully installs locally. But! If I add this repo as a tap with the following:

```
brew tap mattmassicotte/xclint https://github.com/mattmassicotte/XCLint.git
```

This succeeds, but afterwards, homebrew is unable to find the `xclint` formula. I suspect this is directly because of the naming/cask confusion. But I have **no idea** what I'm doing that is confusing it.

**Comment by edwellbrook** [comment]
Had a quick look and seems like you're possibly misunderstanding the tap command?

From Homebrew docs (emphasis mine):

> To install your tap **without installing any formula at the same time**, users can add it with the [brew tap command](https://docs.brew.sh/Taps).

So, `brew tap` clones the repo and registers the formula with homebrew, but does not install it.

> Users can then install your formulae either with brew install foo if there’s no core formula with the same name, or with brew install user/repo/foo to avoid conflicts.

Notes on repo naming:

> If hosted on GitHub, we recommend that the repository’s name start with homebrew- so the short brew tap command can be used. See the [brew manual page](https://docs.brew.sh/Manpage) for more information on repository naming.

Typically(?) there will be two repos. Using Stripe as an example:

Stripe's CLI has a [main repo](https://github.com/stripe/stripe-cli) for their code/executable and then a [secondary repo](https://github.com/stripe/homebrew-stripe-cli) for homebrew. Note the `homebrew-` prefix on the homebrew repo name.

**Comment by mattmassicotte** [comment]
Everything you wrote here is correct. Except! It's totally possible to make the repo that holds the formulas the same as the repo that holds the sources. In the end, your comment on mastodon was it. Everything here was set up right .... except for the spelling of the "Formula" directory. With that fixed, this all totally works. Thank you so much @edwellbrook
